name: "Close finished milestones"
on:
  issues:
    types: [opened, deleted, closed, reopened, milestoned, demilestoned]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  milestone-closer:
    runs-on: ubuntu-latest
    steps:
    - uses: instantish/milestone-closer@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        debug-only: true
        
